version: '3.3'

services:
  postgres.master:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
      PG_MAX_WAL_SENDERS: 8
      PG_WAL_KEEP_SEGMENTS: 32
    volumes:
      - "${DOCKER_ENV_DEV_POSTGRES_DATA_PATH}/replication/master:/var/lib/postgresql/data"
      - "${DOCKER_ENV_DEV_LOG_PATH}/postgres/replication/master:/var/log/postgres"
      - "./master/setup.sh:/docker-entrypoint-initdb.d/setup.sh"
    ports:
      - 7101:5432

  postgres.slave:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
      PGPASSFILE: /var/lib/postgresql/.pgpass
      REPLICATE_FROM: postgres.master
    volumes:
      - "${DOCKER_ENV_DEV_POSTGRES_DATA_PATH}/replication/slave:/var/lib/postgresql/data"
      - "${DOCKER_ENV_DEV_LOG_PATH}/postgres/replication/slave:/var/log/postgres"
      - "./slave/setup.sh:/docker-entrypoint-initdb.d/setup.sh"
    ports:
      - 7202:5432
    links:
      - postgres.master